export const data =[
    {
       team:"Gt",
       Points:20,
       Results:['W','W','L','L','W']
    },
    {
        team:"Lsg",
        Points:18,
        Results:['W','L','L','W','W']
     },
     {
        team:"Rr",
        Points:16,
        Results:['W','L','W','L','L']
     },
     {
        team:"Dc",
        Points:14,
        Results:['W','W','L','W','L']
     },
     {
        team:"Rcb",
        Points:14,
        Results:['L','W','W','L','L']
     },
     {
        team:"Kkr",
        Points:12,
        Results:['L','W','W','L','W']
     },
     {
        team:"Pbks",
        Points:12,
        Results:['L','W','L','W','L']
     },
     {
        team:"Srh",
        Points:12,
        Results:['W','L','L','L','L']
     },
     {
        team:"Csk",
        Points:8,
        Results:['L','L','W','L','W']
     },
     {
        team:"Mi",
        Points:6,
        Results:['L','W','L','W','W']
     },
]
